version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: podcats
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
    links:
      - mysql
    env_file: '.env.docker'
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: podcats
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password